development:
  secret_key_base: ba8398fad16faae7ecc58d610c2c765f21e8263b6fd7aefb51b9bb7aa099109b47c5eacfe80fbf8356556066a3b91c67f364f294c2d9d4887adc9d47edb43686
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

test:
  secret_key_base: aec1829e760722910f22624b1b7aa4cf59a950f346023abc794f7c2c84ce50b40c283fa7a1d584a9486205f6134798bb7a2bdb7c36c2ee3a0438fd68b34bfedf
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
